.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DNSBLOCK" "1" "August 2018" "" ""
.
.SH "NAME"
\fBdnsblock\fR \- Regex Hosts file
.
.SH "MISSION"
It becomes harder and harder to control to whom your computer wants to talk\. While visiting a web page your computer contacts tracking services or even malware platforms all over the world\. This may happen within email programs as well\. Cloud services are fast moving targets with various backends and vendors\. This line of defense focuses on DNS\.
.
.SH "DESCRIPTION"
\fIdnsblock\fR is a NSS library that acts like the /etc/hosts file except that it makes use of regular expressions (PCRE) to match the hostname\. Create a configuration file ~/\.dnsblock and add \fIdnsblock\fR to your /etc/nsswitch\.conf configuration to enable \fIdnsblock\fR\.
.
.SH "INSTALLATION"
There is a simple installation helper for Debian/Ubuntu\. Just run one of the following commands to create a installable package\.
.
.IP "" 4
.
.nf

$ make debian
$ make ubuntu
.
.fi
.
.IP "" 0
.
.P
Otherwise, you may use
.
.IP "" 4
.
.nf

$ make
$ sudo make install
.
.fi
.
.IP "" 0
.
.SH "CONFIGURATION"
/etc/nsswitch\.conf
.
.IP "" 4
.
.nf

hosts: files dnsblock dns
.
.fi
.
.IP "" 0
.
.SH "EXAMPLES"
/etc/dnsblock
.
.IP "" 4
.
.nf

# Early pass\-through for all multicast DNS requests\.
*           \e\.local$

# Block ad servers like adserver\.example\.net\.
127\.0\.0\.1   ^adserver\e\.

# Block tracking servers like tracking123\.somedomain\.com\.
127\.0\.0\.2   ^tracking\ed*\e\.

# Pass\-through some TLDs\.
*           \e\.nl$
*           \e\.se$
*           \e\.org$

# Block everything else\.
127\.0\.0\.3   \.*

Have a look at docs/dnsblock\.example for a real life example\.
.
.fi
.
.IP "" 0
.
.SH "LOGGING"
\fIdnsblock\fR logs all DNS requests to your log environment\.
.
.IP "" 4
.
.nf

$ tail \-f /var/log/messages
$ journalctl \-b \-f
.
.fi
.
.IP "" 0
.
.SH "FILES"
dnsblock reads /etc/dnsblock and $HOME/\.dnsblock in that particular order\. Both files get parsed if they exist\.
.
.SH "CHROME NOTES"
Chrome acts like a full featured OS within your OS and comes with its own DNS resolver\. It was once possible to use the Linux OS DNS resolver\. But it seems like this feature has been disabled now\. Search for \fIexperimental asynchronous DNS client\fR and \fIchrome://flags\fR\.
