.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DNSBLOCK" "1" "March 2015" "" ""
.
.SH "NAME"
\fBdnsblock\fR \- Hosts file with regex support
.
.SH "DESCRIPTION"
\fIdnsblock\fR is a NSS library that acts like the /etc/hosts file except that it makes use of Perl regular expressions (PCRE) to match the hostname\. Create a configuration file ~/\.dnsblock and add \fIdnsblock\fR to your /etc/nsswitch\.conf configuration to enable \fIdnsblock\fR\.
.
.SH "INSTALLATION"
There is a simple installation helper for Debian/Ubuntu\. Just run one of the following commands to create a installable package\.
.
.IP "" 4
.
.nf

$ make debian
$ make ubuntu
.
.fi
.
.IP "" 0
.
.P
Otherwise, you may use
.
.IP "" 4
.
.nf

$ make
$ sudo make install
.
.fi
.
.IP "" 0
.
.SH "CONFIGURATION"
/etc/nsswitch\.conf
.
.IP "" 4
.
.nf

hosts: files dnsblock dns
.
.fi
.
.IP "" 0
.
.SH "EXAMPLES"
/etc/dnsblock
.
.IP "" 4
.
.nf

# Path through all multicast DNS requests
\-           \e\.local$

# Path through all DE domains
\-           \e\.de$

# Block ad servers like adserver\.example\.net
127\.0\.0\.1   ^adserver\e\.

# Block tracking servers like tracking123\.somedomain\.com
127\.0\.0\.2   ^tracking\ed*\e\.

# Block social media plugins that keep tracking you with "Like" buttons
::1         \e\.randombook\e\.(com|net)$

# Block requests to specific TLDs
::1         \e\.(gov|xxx)$
.
.fi
.
.IP "" 0
.
.SH "LOGGING"
\fIdnsblock\fR logs all DNS requests to your log environment\.
.
.IP "" 4
.
.nf

$ tail \-f /var/log/messages
$ journalctl \-b \-f
.
.fi
.
.IP "" 0
.
.SH "FILES"
dnsblock reads /etc/dnsblock and $HOME/\.dnsblock in that particular order\. Both files get parsed if they exist\.
.
.SH "CHROMIUM NOTES"
chromium seems to use its own DNS resolver and bypasses the DNS resolver of your operating system\. You can disable this behaviour by surfing to \fIchrome://flags/\fR\. Disable the \fIexperimental asynchronous DNS client\fR\.
.
.SH "FIREFOX NOTES"
Firefox offers the following plugins, that make your surfing experience extremely uncomfortable\. :)
.
.IP "" 4
.
.nf

* NoScript
* RequestPolicy
* CookieMonster
* Certificate Patrol
* DNSSEC TLSA Validator
* Various Adblockers
.
.fi
.
.IP "" 0

